package main

import (
	"fmt"
	"log"
	"net"
	"net/http"
	"time"

	"google.golang.org/grpc"
	// pb "github.com/user/golang-course/project_c_grpc/proto" // This would be the generated code
)

// ─────── gRPC + REST Microservice ───────
// In a real project, you would run:
// `protoc --go_out=. --go-grpc_out=. user_service.proto`
// This generates the Go structs and interface methods.

// 1. We define a struct that implements the interface generated by protoc.
type userServiceServer struct {
	// pb.UnimplementedUserServiceServer // Required by gRPC for forward compatibility
}

// 2. We implement the GetUser method defined in the .proto file
/*
func (s *userServiceServer) GetUser(ctx context.Context, req *pb.GetUserRequest) (*pb.GetUserResponse, error) {
	// In reality, you would query a database here.
	if req.GetId() == 1 {
		return &pb.GetUserResponse{
			User: &pb.User{
				Id:    1,
				Name:  "Alice",
				Email: "alice@example.com",
			},
		}, nil
	}
	return nil, fmt.Errorf("user not found")
}
*/

// ─────── REST Gateway ───────
// Companies often want to expose the same gRPC service as a standard REST JSON API
// for web clients. The most common way to do this in Go is using grpc-gateway,
// which generates a reverse proxy that translates REST HTTP calls into gRPC calls automatically!

func main() {
	fmt.Println("--- Project C: gRPC & REST Microservice Concept ---")
	fmt.Println("To make this runnable, you must install 'protoc' and the Go plugins:")
	fmt.Println("1. go install google.golang.org/protobuf/cmd/protoc-gen-go@latest")
	fmt.Println("2. go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest")
	fmt.Println("3. protoc --go_out=. --go-grpc_out=. user_service.proto")

	// 1. Setup the Network Listener
	lis, err := net.Listen("tcp", ":50051")
	if err != nil {
		log.Fatalf("failed to listen: %v", err)
	}

	// 2. Create the gRPC Server
	grpcServer := grpc.NewServer()

	// 3. Register our implementation with the gRPC Server
	// pb.RegisterUserServiceServer(grpcServer, &userServiceServer{})
	_ = grpcServer // suppressing unused variable for conceptual demo

	// 4. Start serving (in a goroutine so we don't block)
	go func() {
		fmt.Println("gRPC Server conceptually listening on :50051")
		// grpcServer.Serve(lis)
		_ = lis
	}()

	// 5. (Conceptual) REST Gateway
	go func() {
		// Example HTTP server that acts as a REST facade
		mux := http.NewServeMux()
		mux.HandleFunc("/api/users/", func(w http.ResponseWriter, r *http.Request) {
			// The grpc-gateway would normally handle this translation automatically.
			w.Header().Set("Content-Type", "application/json")
			w.Write([]byte(`{"id": 1, "name": "Alice", "email": "alice@example.com"}`))
		})

		fmt.Println("REST Gateway conceptually listening on :8080")
		http.ListenAndServe(":8080", mux)
	}()

	time.Sleep(500 * time.Millisecond)
	fmt.Println("\nMicroservice architecture conceptually running. Press Ctrl+C to exit.")
}
